{
 "title": "Kubernetes: All Nodes",
 "description": "Dashboard to get an overview of all nodes in a Kubernetes Cluster",
 "tags": [ "prometheus" ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "label": "Namespace", "query": "label_values(namespace)" },
   {
    "name": "instance",
    "label": "Node",
    "query": "label_values(node_memory_Active_bytes, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Pods Running By Namespace",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Running\"})"
    }
   ]
  },
  {
   "title": "Pods Pending By Namespace",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Pending\"})"
    }
   ]
  },
  {
   "title": "Pods Failed By Namespace",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\",  phase=\"Failed\"})"
    }
   ]
  },
  {
   "title": "Memory Usage By Node",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "((sum(node_memory_MemTotal_bytes {instance=~\"[[instance]]:.*\"}) - sum(node_memory_MemFree_bytes{instance=~\"[[instance]]:.*\"}) - sum(node_memory_Buffers_bytes{instance=~\"[[instance]]:.*\"}) - sum(node_memory_Cached_bytes{instance=~\"[[instance]]:.*\"})) / sum(node_memory_MemTotal_bytes{instance=~\"[[instance]]:.*\"})) * 100"
    }
   ]
  },
  {
   "title": "Disk Space Usage By Node",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(node_filesystem_size_bytes{device!=\"rootfs\", instance=~\"[[instance]]:.*\"}) - sum(node_filesystem_free_bytes{device!=\"rootfs\", instance=~\"[[instance]]:.*\"})) / sum(node_filesystem_size_bytes{device!=\"rootfs\", instance=~\"[[instance]]:.*\"})"
    }
   ]
  },
  {
   "title": "Free Bytes of Memory By Node",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "label_replace (sum  by (instance) (node_memory_MemFree_bytes{instance=~\"[[instance]]:.*\"}), \"node_ip\", \"$1\",  \"instance\", \"(.*):.*\") ",
     "legendFormat": "{{node_ip}} "
    }
   ]
  },
  {
   "title": "5m System Load By Node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "label_replace(sum by (instance)(node_load5{instance=~\"[[instance]]:.*\"}), \"node_ip\", \"$1\",  \"instance\", \"(.*):.*\")",
     "legendFormat": "{{node_ip}}"
    }
   ]
  },
  {
   "title": "Disk Writes in Bytes by Node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "label_replace (sum by (instance)(rate(node_disk_written_bytes_total{instance=~\"[[instance]]:.*\"}[5m])) , \"node_ip\", \"$1\",  \"instance\", \"(.*):.*\")  ",
     "legendFormat": "{{node_ip}}"
    }
   ]
  },
  {
   "title": "Idle CPU By Node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "percent", "label": "cpu usage" }
   ],
   "targets": [
    {
     "expr": "\n label_replace (sum by (instance) (rate(node_cpu_seconds_total{instance=~\"[[instance]]:.*\"}[5m])), \"node_ip\", \"$1\",  \"instance\", \"(.*):.*\") ",
     "legendFormat": "{{node_ip}} "
    }
   ]
  },
  {
   "title": "Network Transmitted Bytes By Node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "label_replace (sum by (instance)(rate(node_network_transmit_bytes_total{device!~\"lo\", instance=~\"[[instance]]:.*\"}[5m])), \"node_ip\", \"$1\",  \"instance\", \"(.*):.*\")",
     "legendFormat": " {{node_ip}}"
    }
   ]
  },
  {
   "title": "Network Received Bytes By Node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "label_replace(sum by (instance)(rate(node_network_receive_bytes_total{device!~\"lo\", instance=~\"[[instance]]:.*\"}[5m])), \"node_ip\", \"$1\",  \"instance\", \"(.*):.*\")",
     "legendFormat": "{{node_ip}}"
    }
   ]
  }
 ]
}