{
 "title": "Pipeline Health",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "dataset_id",
    "query": "label_values(kafka_topic_partition_current_offset, topic)"
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Pipeline Topics Input",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_topic_partition_current_offset{kubernetes_namespace=\"streaming-prime\",  topic=~\".*([[dataset_id]]).*\"}[2m]) > 0) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Log Messages per Second per App",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Log Messages per Sec." }
   ],
   "targets": [
    {
     "expr": "sum(label_replace(rate(fluentd_input_status_num_records_total{tag=~\".*(forklift|reaper|voltron|valkyrie|odo).*\"}[5m]), \"name\", \"$1\", \"tag\", \"kube.var.log.containers.(.+?)-.*\")) by (name) > 0",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Current Lag (By Consumer Group)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{kubernetes_namespace=\"streaming-prime\", topic=~\".*([[dataset_id]]).*\", consumergroup!~\"console.*\"} > 0) by (consumergroup, topic, dataset)",
     "legendFormat": "{{consumergroup}}"
    }
   ]
  },
  {
   "title": "Rate of Data Ingest to Presto",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "bytes", "label": "Data per second (est.)" }
   ],
   "targets": [
    {
     "expr": "sum(rate(com_facebook_presto_hive_HiveWriterStats_InputPageSizeInBytes_AllTime_Total[5m]))",
     "legendFormat": "Input"
    }
   ]
  },
  {
   "title": "Active Microservice Instances",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "Number of Active Instances" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{container=~\"(andi|forklift|valkyrie|reaper)\"}) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Apps in Crash Loops",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(kube_pod_container_status_restarts_total[5m]) > 0) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Topic Usage",
   "type": "gauge",
   "description": "Percent of topics in the pipeline that have data flowing through them.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "count(sum(rate(kafka_topic_partition_current_offset{kubernetes_namespace=\"streaming-prime\"}[2m]) > 0) by (topic)) / count(sum(kafka_topic_partition_current_offset{kubernetes_namespace=\"streaming-prime\"}) by (topic))"
    }
   ]
  }
 ]
}