{
 "title": "Hadoop Cluster Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Hadoop NodeManager Memory Use",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "alias": "Memory Free",
     "app": "nodemanager",
     "metric": "mem_free",
     "precision": "default",
     "transform": "none"
    },
    {
     "aggregator": "avg",
     "alias": "Memory Used",
     "app": "nodemanager",
     "metric": "mem_used",
     "precision": "default",
     "transform": "none"
    }
   ]
  },
  {
   "title": "Ambari Server CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 4, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "alias": "Total Threads",
     "app": "ambari_server",
     "metric": "jvm.threads.count",
     "precision": "default",
     "transform": "none"
    },
    {
     "aggregator": "avg",
     "alias": "Waiting",
     "app": "ambari_server",
     "metric": "jvm.threads.waiting.count",
     "precision": "default",
     "transform": "none"
    },
    {
     "aggregator": "avg",
     "alias": "Deadlocked",
     "app": "ambari_server",
     "metric": "jvm.threads.deadlock.count",
     "precision": "default",
     "transform": "none"
    },
    {
     "aggregator": "avg",
     "alias": "New",
     "app": "ambari_server",
     "metric": "jvm.threads.new.count",
     "precision": "default",
     "transform": "none"
    },
    {
     "aggregator": "avg",
     "alias": "Blocked",
     "app": "ambari_server",
     "metric": "jvm.threads.blocked.count",
     "precision": "default",
     "transform": "none"
    },
    {
     "aggregator": "avg",
     "alias": "Runnable",
     "app": "ambari_server",
     "metric": "jvm.threads.runnable.count",
     "precision": "default",
     "transform": "none"
    },
    {
     "aggregator": "avg",
     "alias": "Terminated",
     "app": "ambari_server",
     "metric": "jvm.threads.terminated.count",
     "precision": "default",
     "transform": "none"
    },
    {
     "aggregator": "avg",
     "alias": "Timed Waiting",
     "app": "ambari_server",
     "metric": "jvm.threads.timed_waiting.count",
     "precision": "default",
     "transform": "none"
    }
   ]
  },
  {
   "title": "Hadoop NodeManager Disk Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "alias": "Disk Free",
     "app": "nodemanager",
     "metric": "disk_free",
     "precision": "default",
     "transform": "none"
    },
    {
     "aggregator": "avg",
     "alias": "Disk Used",
     "app": "nodemanager",
     "metric": "disk_used",
     "precision": "default",
     "transform": "none"
    }
   ]
  },
  {
   "title": "Hadoop NodeManager Reported CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Percent Usage" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "alias": "User",
     "app": "nodemanager",
     "metric": "cpu_user",
     "precision": "default",
     "transform": "none"
    },
    {
     "aggregator": "avg",
     "alias": "System",
     "app": "nodemanager",
     "metric": "cpu_system",
     "precision": "default",
     "transform": "none"
    }
   ]
  },
  {
   "title": "NodeManager Server CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 4, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "alias": "Waiting",
     "app": "nodemanager",
     "metric": "jvm.JvmMetrics.ThreadsWaiting",
     "precision": "default",
     "transform": "none"
    },
    {
     "aggregator": "avg",
     "alias": "Runnable",
     "app": "nodemanager",
     "metric": "jvm.JvmMetrics.ThreadsRunnable",
     "precision": "default",
     "transform": "none"
    },
    {
     "aggregator": "avg",
     "alias": "New",
     "app": "nodemanager",
     "metric": "jvm.JvmMetrics.ThreadsNew",
     "precision": "default",
     "transform": "none"
    },
    {
     "aggregator": "avg",
     "alias": "Blocked",
     "app": "nodemanager",
     "metric": "jvm.JvmMetrics.ThreadsBlocked",
     "precision": "default",
     "transform": "none"
    },
    {
     "aggregator": "avg",
     "alias": "Terminated",
     "app": "nodemanager",
     "metric": "jvm.JvmMetrics.ThreadsTerminated",
     "precision": "default",
     "transform": "none"
    },
    {
     "aggregator": "avg",
     "alias": "Timed Waiting",
     "app": "nodemanager",
     "metric": "jvm.JvmMetrics.ThreadsTimedWaiting",
     "precision": "default",
     "transform": "none"
    }
   ]
  },
  {
   "title": "Region Server  Network Traffic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "alias": "Bytes Received",
     "app": "ams-hbase",
     "metric": "regionserver.RegionServer.receivedBytes",
     "precision": "default",
     "region": "default",
     "statistics": [ "Average" ],
     "transform": "none"
    },
    {
     "aggregator": "avg",
     "alias": "Bytes Sent",
     "app": "ams-hbase",
     "metric": "regionserver.RegionServer.sentBytes",
     "precision": "default",
     "region": "default",
     "statistics": [ "Average" ],
     "transform": "none"
    }
   ]
  },
  {
   "title": "Hadoop NodeManager Disk IO",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "alias": "Read",
     "app": "nodemanager",
     "metric": "read_bytes",
     "precision": "default",
     "transform": "none"
    },
    {
     "aggregator": "avg",
     "alias": "Write",
     "app": "nodemanager",
     "metric": "write_bytes",
     "precision": "default",
     "transform": "none"
    }
   ]
  },
  {
   "title": "hbase Server CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 4, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "alias": "Waiting",
     "app": "ams-hbase",
     "metric": "jvm.Master.JvmMetrics.ThreadsWaiting",
     "precision": "default",
     "transform": "none"
    },
    {
     "aggregator": "avg",
     "alias": "New",
     "app": "ams-hbase",
     "metric": "jvm.Master.JvmMetrics.ThreadsNew",
     "precision": "default",
     "transform": "none"
    },
    {
     "aggregator": "avg",
     "alias": "Blocked",
     "app": "ams-hbase",
     "metric": "jvm.Master.JvmMetrics.ThreadsBlocked",
     "precision": "default",
     "transform": "none"
    },
    {
     "aggregator": "avg",
     "alias": "Runnable",
     "app": "ams-hbase",
     "metric": "jvm.Master.JvmMetrics.ThreadsRunnable",
     "precision": "default",
     "transform": "none"
    },
    {
     "aggregator": "avg",
     "alias": "Terminated",
     "app": "ams-hbase",
     "metric": "jvm.Master.JvmMetrics.ThreadsTerminated",
     "precision": "default",
     "transform": "none"
    },
    {
     "aggregator": "avg",
     "alias": "Timed Waiting",
     "app": "ams-hbase",
     "metric": "jvm.Master.JvmMetrics.ThreadsTimedWaiting",
     "precision": "default",
     "transform": "none"
    }
   ]
  },
  {
   "title": "RDS Storage Free",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "alias": "Kylo DB",
     "dimensions": { "DBInstanceIdentifier": "prod-kylo" },
     "metricName": "FreeStorageSpace",
     "namespace": "AWS/RDS",
     "precision": "default",
     "region": "us-west-2",
     "statistics": [ "Average" ],
     "transform": "none"
    }
   ]
  }
 ]
}