{
 "title": "SCOS Cluster Overview",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "namespace", "label": "Namespace", "query": "label_values(namespace)" }
  ]
 },
 "panels": [
  {
   "title": "Waiting",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kube_pod_container_status_waiting{namespace=~\"$namespace\"} == 1)",
     "legendFormat": "Total Pods"
    }
   ]
  },
  {
   "title": "Containers in State",
   "type": "graph",
   "gridPos": { "h": 9, "w": 5, "x": 2, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(kube_pod_container_status_running{namespace=~\"$namespace\"} == 1)",
     "legendFormat": "Running"
    },
    {
     "expr": "count(kube_pod_container_status_terminated{namespace=~\"$namespace\"} == 1)",
     "legendFormat": "Terminated"
    },
    {
     "expr": "count(kube_pod_container_status_waiting{namespace=~\"$namespace\"} == 1)",
     "legendFormat": "Waiting"
    }
   ]
  },
  {
   "title": "Pod Termination Reasons",
   "type": "graph",
   "gridPos": { "h": 9, "w": 5, "x": 7, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Pods" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_terminated_reason{namespace=~\"$namespace\"}) by (reason) > 0",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "CPU Usage Per Container",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(sum(\n    label_replace(\n        label_replace(\n            container_cpu_cfs_throttled_periods_total{container_name!=\"\", container_name!=\"POD\", namespace=~\"$namespace\"}, #ignore pod parent cgroup\n            \"container\",        #new label\n            \"$0\",               #the whole shebang\n            \"container_name\",   #label to replace\n            \".*\"                #match the entire contents\n            )\n        ,      #nested label_replace once for each label in your group by....\n        \"pod\",\n        \"$0\",\n        \"pod_name\",\n        \".*\"\n    )\n) by (pod, container)\n/\nsum(\n    label_replace(\n        label_replace(\n            container_cpu_cfs_periods_total{container_name!=\"\", container_name!=\"POD\", namespace=~\"$namespace\"}, #ignore pod parent cgroup\n            \"container\",        #new label\n            \"$0\",               #the whole shebang\n            \"container_name\",   #label to replace\n            \".*\"                #match the entire contents\n            )\n        ,      #nested label_replace once for each label in your group by....\n        \"pod\",\n        \"$0\",\n        \"pod_name\",\n        \".*\"\n    )\n) by (pod, container)) by (container)\n",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Terminated (in Error)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_terminated_reason{namespace=~\"$namespace\", reason=\"Error\"}) by (reason) > 0",
     "legendFormat": "Total Pods"
    }
   ]
  },
  {
   "title": "Running",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(kube_pod_container_status_running{namespace=~\"$namespace\"} == 1)",
     "legendFormat": "Total Pods"
    }
   ]
  },
  {
   "title": "Total Containers",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(kube_pod_container_status_ready{namespace=~\"$namespace\"})",
     "legendFormat": "Total Pods"
    }
   ]
  },
  {
   "title": "Over-Provisioned: Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(sum(\n    label_replace(\n        label_replace(\n            container_memory_usage_bytes{container_name!=\"\", container_name!=\"POD\", namespace=~\"$namespace\"}, #ignore pod parent cgroup\n            \"container\",        #new label\n            \"$0\",               #the whole shebang\n            \"container_name\",   #label to replace\n            \".*\"                #match the entire contents\n            )\n        ,      #nested label_replace once for each label in your group by....\n        \"pod\",\n        \"$0\",\n        \"pod_name\",\n        \".*\"\n    )\n) by (pod, container)\n/\nsum(\n    kube_pod_container_resource_limits_memory_bytes{container!=\"\", container!=\"POD\", namespace=~\"$namespace\"}\n) by (pod, container)) by (container) < 0.5",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Under-Provisioned: Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(sum(\n    label_replace(\n        label_replace(\n            container_memory_usage_bytes{container_name!=\"\", container_name!=\"POD\", namespace=~\"$namespace\"}, #ignore pod parent cgroup\n            \"container\",        #new label\n            \"$0\",               #the whole shebang\n            \"container_name\",   #label to replace\n            \".*\"                #match the entire contents\n            )\n        ,      #nested label_replace once for each label in your group by....\n        \"pod\",\n        \"$0\",\n        \"pod_name\",\n        \".*\"\n    )\n) by (pod, container)\n/\nsum(\n    kube_pod_container_resource_limits_memory_bytes{container!=\"\", container!=\"POD\", namespace=~\"$namespace\"}\n) by (pod, container)) by (container) > 0.5",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Pod Termination Details",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 6, "y": 17 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_terminated_reason{namespace=~\"$namespace\", reason!~\"Completed\"}) by (pod, container, reason) > 0"
    }
   ]
  }
 ]
}